logging:
  level: INFO
  loggers:
    net.zetlan.examples: DEBUG
#    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: WARN
    org.hibernate.orm.deprecation: ERROR
    log4j.logger.org.hibernate.SQL: DEBUG
    log4j.logger.org.hibernate.type.descriptor.sql: TRACE
serviceName: USER

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
