logging:
  level: INFO
  loggers:
    net.zetlan.examples: DEBUG

serviceName: TEST

server:
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

database:
  url: jdbc:h2:./db/h2database;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=10000
  driverClass: org.h2.Driver
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
  validationQuery: "/* Application Health Check */ SELECT 1"
