logging:
  level: INFO
  loggers:
    net.zetlan.examples: DEBUG
#    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: WARN
    org.hibernate.orm.deprecation: ERROR
    log4j.logger.org.hibernate.SQL: DEBUG
    log4j.logger.org.hibernate.type.descriptor.sql: TRACE
serviceName: TEST

server:
  applicationConnectors:
    - type: http
      port: 8010
  adminConnectors:
    - type: http
      port: 8011

services:
  - serviceName: USER
    baseUri: http://localhost:8080
